env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[1e4bfe76d933bdff3a61udb9529d60287b19bff7e61797b027ac3df52af879bb5a9d03d72cd0880ff1c01871b31d1e7a"


task:
    name: Buildbomt
    timeout_in: 122m
    container:
      image: mrkhan007/aosp:latest
      cpu: 4
      memory: 12G    
    sync_script:
      - bash sync
    build_script:
      - bash build
#start build 

