#!/bin/bash
cd /tmp/rec
rm -rf .repo
cd /tmp/rec
source build/envsetup.sh
lunch omni_rmx2020-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export ALLOW_MISSING_DEPENDENCIES=true
cd /tmp/rec
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

make_rec(){
	mka recoveryimage
	curl -sL https://git.io/file-transfer | sh
	./transfer out/target/product/RMX2020/recovery.img
    ./transfer out/target/product/RMX2020.zip
    ./transfer out/target/product/RMX2020/*Official*.zip
	./transfer out/target/product/RMX2020/*OFFICIAL*.zip
	./transfer out/target/product/RMX2020/*SHRP*.zip
    ./transfer out/target/product/RMX2020/*Add*.zip
	./transfer gof out/target/product/RMX2020/recovery.img
    ./transfer gof out/target/product/RMX2020.zip
    ./transfer gof out/target/product/RMX2020/*Official*.zip
	./transfer gof out/target/product/RMX2020/*OFFICIAL*.zip
	./transfer gof out/target/product/RMX2020/*SHRP*.zip
    ./transfer gof out/target/product/RMX2020/*Add*.zip
}

make_rec
