#!/bin/bash
cd /tmp/rom
rm -rf .repo
cd external/selinux 
curl -L http://ix.io/2FhM > sasta.patch 
git am sasta.patch 
cd /tmp/rom
cd frameworks/av 
wget https://github.com/phhusson/platform_frameworks_av/commit/624cfc90b8bedb024f289772960f3cd7072fa940.patch 
patch -p1 < *.patch
cd /tmp/rom
cd frameworks/opt/net/wifi
wget https://raw.githubusercontent.com/SamarV-121/android_vendor_extra/lineage-18.1/patches/frameworks/opt/net/wifi/0001-wifi-Add-StaState-API.patch
patch -p1 < *.patch
cd /tmp/rom
cd frameworks/opt/net/ims
wget https://raw.githubusercontent.com/SamarV-121/android_vendor_extra/lineage-18.1/patches/frameworks/opt/net/ims/0001-Partially-Revert-Remove-references-to-deprecated-dev.patch
patch -p1 < *.patch
cd /tmp/rom
cd frameworks/base 
wget https://raw.githubusercontent.com/SamarV-121/android_vendor_extra/lineage-18.1/patches/frameworks/base/0008-WifiManager-Add-StaState-API.patch
patch -p1 < *.patch
cd /tmp/rom
source build/envsetup.sh
lunch aosp_RMX1941-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	mka recoveryimage
	zip=$(up out/target/product/RMX1941/recovery.img)
	echo " "
	echo "$zip"
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/RMX1941/recovery.img
}

make_metalava
make_rom &
sleep 4500 && kill "$!"
