#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/lollosfork.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf lollosfork.tar.gz
echo "unzip done"
find lollosfork.tar.gz -delete
